# Generated by Django 5.1.4 on 2025-07-07 10:52

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresaprimaria', '0001_initial'),
        ('zeladorx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('empresaprimaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaPrimaria', to='empresaprimaria.empresaprimaria')),
                ('setor', models.ManyToManyField(max_length=40, to='zeladorx.typezeladoria')),
            ],
        ),
    ]
