# Generated by Django 5.1.4 on 2025-07-07 10:52

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsFromProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('document', models.FileField(blank=True, max_length=2000, upload_to='documents/%Y/%m/%d/')),
            ],
        ),
    ]
