# Generated by Django 5.1.4 on 2025-07-07 10:52

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_de_servicos', '0001_initial'),
        ('localidade', '0001_initial'),
        ('terrenos', '0001_initial'),
        ('vegetacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dimensao', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, max_length=2000, upload_to='areaslimpezapredial/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidadelimpezapredial', to='localidade.localidadelimpezapredial')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicocatalogoservicolimpezapredial', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
            ],
            options={
                'unique_together': {('nome', 'localidade')},
            },
        ),
        migrations.CreateModel(
            name='AreasJardins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dimensao', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, max_length=2000, upload_to='areasverdes/%Y/%m/%d/')),
                ('periodicidade', models.CharField(choices=[('Mensal', 'Mensal'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=30)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('Terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rTerrenoAreas', to='terrenos.terreno')),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidadeareas', to='localidade.localidadejardiangem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicocatalogoservico', to='catalogo_de_servicos.catalogodeservicojardinagem')),
                ('vegetacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetacaocatalogovegetacao', to='vegetacao.catalogovegetacao')),
            ],
            options={
                'unique_together': {('nome', 'vegetacao', 'Terreno')},
            },
        ),
    ]
