# Generated by Django 5.1.4 on 2025-07-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arealimpezapredial',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='areasjardins',
            unique_together=set(),
        ),
    ]
