# Generated by Django 5.1.4 on 2025-08-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogovegetacao',
            unique_together=set(),
        ),
    ]
