# Generated by Django 5.1.4 on 2025-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasdasemana', models.CharField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=60, unique=True)),
            ],
        ),
    ]
