# Generated by Django 5.1.4 on 2025-08-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terreno',
            unique_together=set(),
        ),
    ]
