# Generated by Django 5.1.4 on 2025-07-07 10:52

import django.db.models.deletion
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingServicosGerenteJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('NotificationsServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosAgendados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportProductivity', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosJardinagemGerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettingServicosGerenteLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('NotificationsServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosAgendados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportProductivity', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosLimpezaPredialGerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
