# Generated by Django 5.1.4 on 2025-07-07 10:52

import datetime
import django.db.models.deletion
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('catalogo_de_servicos', '0001_initial'),
        ('semana', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoJardinagemAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('id_configuracao', models.CharField(blank=True, max_length=20, null=True)),
                ('DataDeInicio', models.DateTimeField()),
                ('DescricaoDoServico', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Agendado', max_length=60)),
                ('foto_solicitacao', models.ImageField(blank=True, max_length=2000, upload_to='solicitacao_servico_jardinagem/%Y/%m/%d/')),
                ('foto_entrega', models.ImageField(blank=True, max_length=2000, upload_to='entrega_servico_jardinagem/%Y/%m/%d/')),
                ('DataDeConclusao', models.DateTimeField(blank=True, null=True)),
                ('TipoServico', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Extra', 'Extra'), ('Automático', 'Automático')], default='Regular', max_length=30, null=True)),
                ('ServicoCompunsivo', models.BooleanField(blank=True, default=False, null=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RAreasServicoAgendado', to='areas.areasjardins')),
                ('ColaboradoresConfirmados', models.ManyToManyField(blank=True, null=True, related_name='RColaboradoresConfirmados', to=settings.AUTH_USER_MODEL)),
                ('ColaboradoresEscalados', models.ManyToManyField(related_name='RColaboradoresEscaladosServicoAgendado', to=settings.AUTH_USER_MODEL)),
                ('ColaboradoresNegados', models.ManyToManyField(blank=True, null=True, related_name='RColaboradoresNegados', to=settings.AUTH_USER_MODEL)),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosServicoAgendado', to='catalogo_de_servicos.catalogodeservicojardinagem')),
            ],
        ),
        migrations.CreateModel(
            name='FatoServicoJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('data_hora_chegada_na_area', models.DateTimeField()),
                ('data_hora_retorno_area', models.DateTimeField()),
                ('Gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RColaboradorFatoServico', to=settings.AUTH_USER_MODEL)),
                ('Servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RServicoServicoAgendado', to='servicos.servicojardinagemagendado')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoJardinagemConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('tempomedioplanejado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('horario_1', models.TimeField()),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RareaJardinagemconfigurado', to='areas.areasjardins')),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosJardinagemServicoConfigurado', to='catalogo_de_servicos.catalogodeservicojardinagem')),
                ('diasaseremrealizado', models.ManyToManyField(related_name='Rdiasdasemanaconfiguracoesjardinagem', to='semana.diasdasemana')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoLimpezaPredialAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('id_configuracao', models.CharField(blank=True, max_length=20, null=True)),
                ('DataDeInicio', models.DateTimeField(blank=True, null=True)),
                ('DataDeConclusao', models.DateTimeField(blank=True, null=True)),
                ('DescricaoDoServico', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Agendado', max_length=60)),
                ('TipoServico', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Extra', 'Extra'), ('Automático', 'Automático')], default='Regular', max_length=30, null=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rarealimpezapredialagendado', to='areas.arealimpezapredial')),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosLimpezaPredialServicoAgendado', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
            ],
        ),
        migrations.CreateModel(
            name='FatoServicoLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('data_hora_chegada_na_area', models.DateTimeField()),
                ('data_hora_retorno_area', models.DateTimeField()),
                ('foto_entrega', models.ImageField(blank=True, max_length=2000, null=True, upload_to='entrega_servico_limpeza_predial/%Y/%m/%d/')),
                ('Gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RColaboradorFatoServicoLimpezaPredial', to=settings.AUTH_USER_MODEL)),
                ('Servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RServicoServicoLimpezaPredialAgendado', to='servicos.servicolimpezapredialagendado')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoLimpezaPredialConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('tempomedioplanejado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('horario_1', models.TimeField()),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rarealimpezapredialconfigurado', to='areas.arealimpezapredial')),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosLimpezaPredialServicoConfigurado', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
                ('diasaseremrealizado', models.ManyToManyField(related_name='Rdiasdasemanaconfiguracoeslimpezapreidal', to='semana.diasdasemana')),
            ],
        ),
    ]
