# Generated by Django 5.1.4 on 2025-07-07 10:52

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogodeServicoJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoJardiangem', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
        migrations.CreateModel(
            name='CatalogodeServicoLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoLimpezaPredial', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
    ]
