"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from django.contrib.messages import constants as messages


load_dotenv()

# ============================================================
# BASE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = str(os.getenv('SECRET_KEY'))

DEBUG = True

ALLOWED_HOSTS = ['*']


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ============================================================
# AUTHENTICATION
# ============================================================

AUTH_USER_MODEL = 'gerente.Gerente'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'gerente.backends.CaseInsensitiveModelBackend',
)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'areas.apps.AreasConfig',
    'catalogo_de_servicos.apps.CatalogoDeServicosConfig',
    'dashboards.apps.DashboardsConfig',
    'empresaprimaria.apps.EmpresaprimariaConfig',
    'empresasecundario.apps.EmpresasecundarioConfig',
    'gerente.apps.GerenteConfig',
    'localidade.apps.LocalidadeConfig',
    'relatorios.apps.RelatoriosConfig',
    'terrenos.apps.TerrenosConfig',
    'unidade.apps.UnidadeConfig',
    'utils.apps.UtilsConfig',
    'vegetacao.apps.VegetacaoConfig',
    'servicos.apps.ServicosConfig',
    'settings.apps.SettingsConfig',
    'schedules.apps.SchedulesConfig',
    'semana.apps.SemanaConfig',
    'authenticate.apps.AuthenticateConfig',
    'permissionscontrol.apps.PermissionscontrolConfig',
    'zeladorx.apps.ZeladorxConfig',
    'checklists.apps.ChecklistsConfig',
    'medidor.apps.MedidorConfig',
    'retornos.apps.RetornosConfig',

    'rest_framework',
    'rest_framework.authtoken',

    # Mantido somente se alguma parte do projeto importar
    # diretamente django-storages.
    # 'storages',
]


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 15,
}


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URLS
# ============================================================

ROOT_URLCONF = 'setup.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'zeladorx.context_processors.create_global_parameters',

                'zeladorx.context_processors.define_wallet',

                'authenticate.context_processors.classicate_login',
            ],
        },
    },
]


# ============================================================
# CHANNELS / WEBSOCKETS
# ============================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'setup.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'zeladorx',

        'USER': 'postgres',

        'PASSWORD': 'PnCdEL',

        'HOST': 'localhost',

        'PORT': '5432',
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES - LOCAL
# ============================================================

# Arquivos estáticos adicionais do projeto
#
# Exemplo:
# CHATCHANNELS/
# └── setup/
#     └── static/
#         ├── css/
#         ├── js/
#         └── images/

STATICFILES_DIRS = [
    BASE_DIR / 'setup' / 'static',
]


# Diretório para onde o collectstatic vai copiar
#
# python manage.py collectstatic

STATIC_ROOT = BASE_DIR / 'static'


# URL pública dos arquivos estáticos

STATIC_URL = '/static/'


# ============================================================
# MEDIA FILES - LOCAL
# ============================================================

# Arquivos enviados pelos usuários:
#
# media/
# ├── imagens/
# ├── documentos/
# └── ...

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'


# ============================================================
# STORAGE - LOCAL
# ============================================================

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ============================================================
# GOOGLE CLOUD STORAGE
# ============================================================

# DESATIVADO
#
# O projeto agora utiliza armazenamento local.
#
# Antes:
#
# from google.oauth2 import service_account
#
# GS_PROJECT_ID = "bucketzeladorx"
#
# GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
#     os.path.join(
#         BASE_DIR,
#         "bucketzeladorx-047b955782da.json"
#     )
# )
#
# STORAGES com GoogleCloudStorage também foi removido.


# ============================================================
# MESSAGES
# ============================================================

MESSAGE_TAGS = {
    messages.ERROR: 'danger',

    messages.SUCCESS: 'success',

    messages.WARNING: 'warning',

    messages.INFO: 'info',
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'