# Generated by Django 5.1.4 on 2025-07-07 10:52

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('linkmapajardinagem', models.CharField(blank=True, max_length=300, null=True)),
                ('linkmapalimnpezapredial', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('empresasecundaria', models.ManyToManyField(related_name='REmpresaSecundariaUnidade', to='empresasecundario.empresasecundaria')),
            ],
        ),
    ]
