# Generated by Django 5.1.4 on 2025-07-07 10:52

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('foto_comprovacao', models.ImageField(blank=True, null=True, upload_to='checklist_jardinagem/%Y/%m/%d/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servico_agendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rServicoAgendadosToChecklist', to='servicos.servicojardinagemagendado')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('foto_comprovacao', models.ImageField(blank=True, null=True, upload_to='checklist_limpeza_predial/%Y/%m/%d/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servico_agendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rTerrenoAreas', to='servicos.servicolimpezapredialagendado')),
            ],
        ),
    ]
